version: '3.5'

services:
  apr:
    container_name: apr
    build:
      context: docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=apr
    ports:
      - '1000:8000'
    networks:
      - apr-network
    depends_on:
      - apr-postgres

  apr-postgres:
    container_name: apr-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: apr
    volumes:
      - apr-postgres-pgsql-data:/var/lib/postgresql/data:rw
    networks:
      - apr-network

networks:
  apr-network:

volumes:
  apr-postgres-pgsql-data:
